# Crisis Indicator

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Define function to calculate crisis indicator based on the 4 macroeconomic factors

def crisis_indicators(dataset):
    crisis_indicators_list = []

    for index, row in dataset.iterrows():
        year = row['Year']
        gdp = row['GDP per Capita Growth (Annual %)']
        inflation = row['Inflation Consumer Prices (Annual %)']
        unemployment = row['Unemployment rate_Ireland_Total_Native-born']

        # Get inflation values for the current and previous year
        inflation_current_year = inflation
        inflation_previous_year = dataset.loc[index - 1, 'Inflation Consumer Prices (Annual %)'] if index > 0 else None
        
        # Get unemployment values for the current and previous year
        unemployment_current_year = unemployment
        unemployment_previous_year = dataset.loc[index - 1, 'Unemployment rate_Ireland_Total_Native-born'] if index > 0 else None
        

        # Calculate crisis indicator for the current year
        crisis_indicator = 0
        
        # Check GDP (if negative, it is a crisis indicator)
        if gdp <= 0:
            crisis_indicator += 1
        
        # Check Inflation (if inflation is decreasing, it is a crisis indicator)
        if inflation_previous_year is not None and inflation_current_year < inflation_previous_year:
            crisis_indicator += 1
        
        # Check Unemployment (if unemployment is increasing, it is a crisis indicator)
        if unemployment_previous_year is not None and unemployment_current_year > unemployment_previous_year:
            crisis_indicator += 1

        # Append year and crisis indicator to the list
        crisis_indicators_list.append({'Year': year, 'Crisis Indicator': crisis_indicator})

    # Create a new DataFrame from the list of dictionaries
    crisis_indicators_df = pd.DataFrame(crisis_indicators_list)

    return crisis_indicators_df

In [3]:
Final = pd.read_excel('Data/FinalData.xlsx')

In [4]:
crisis_df = crisis_indicators(Final)
crisis_df.tail(n=10)

      Year  Crisis Indicator
64  2015.0                 1
65  2016.0                 0
66  2017.0                 0
67  2018.0                 0
68  2019.0                 0
69  2020.0                 2
70  2021.0                 1
71  2022.0                 0
72  2023.0                 0
73  2024.0                 0

In [5]:
# turn Year to 
crisis_df['Year'] = crisis_df['Year'].astype(int)

In [6]:
# combine Combined_All_w_CSO with BRA08
Final = Final.merge(crisis_df, on='Year', how='outer')
Final.tail()

,Year,Annual births,Annual deaths,Emigrants,Immigrants,Net migration,Inflation Consumer Prices (Annual %),GDP Growth (annual %),GDP per Capita Growth (Annual %),Inflation GDP Deflator (Annual %),...,Immigrants_Other countries (23),Immigrants_United Kingdom (1),Immigrants_United States,Net migration_All countries,Net migration_EU14 excl Irl (UK & Ireland),Net migration_EU15 to EU27 (accession countries joined post 2004),Net migration_Other countries (23),Net migration_United Kingdom (1),Net migration_United States,Crisis Indicator
69,2020,59100.0,32400.0,50900.0,95600.0,44700.0,-0.3,6.6,5.5,-1.2,...,36400.0,17600.0,6000.0,44700.0,4800.0,1300.0,27700.0,7900.0,700.0,2
70,2021,57300.0,34300.0,52300.0,74100.0,21800.0,2.4,15.1,14.0,0.5,...,18400.0,21700.0,5500.0,21800.0,-3200.0,4300.0,5900.0,4100.0,3100.0,1
71,2022,59700.0,33600.0,56100.0,107800.0,51700.0,7.8,9.4,7.4,6.6,...,60500.0,12800.0,4300.0,51700.0,-4700.0,11800.0,49800.0,-600.0,-2000.0,0
72,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75800.0,18400.0,5900.0,77700.0,3800.0,100.0,64100.0,3800.0,1000.0,0
73,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [7]:
# save dataset to excel
Final.to_excel('Data/FinalData2.xlsx', index=False)